### ISSUE TITLE
How to setup network / url access to instance correctly?

### ISSUE THREAD

**Issue by moorage** [willkessler/nvidia-docker-novnc#2]
It would be great to have documentation in the README.  that refers to how networking should be setup to the instance.

When executing `/run.sh`, the output ends in something like this:

```
Navigate to this URL:

    http://5e1e573deXYZ:40001/vnc.html?host=5e1e573deXYZ&port=40001
```

On google cloud, does one just open port 40001 and access the external IP address, like actually navigating to `http://216.3.128.12:40001/vnc.html?host=216.3.128.12&port=40001` (just an example)?

Or is url mapping needed?

**Comment by moorage** [comment]
20 GB seemed to work.

**Comment by moorage** [comment]
I successfully created the firewall rule this way:

* Name: `novnc-40001`
* Network: `default`
* Priority: `976`
* Direction: `Ingress`
* Action on match: `Allow`
* Targets \ Target tags: `novnc-40001`
* Source filters \ IP ranges: `0.0.0.0/0`
* Protocols and ports: `tcp:40001`

And then I added it as a network tag on the instance:

* Network tags: `novnc-40001`


Then I accessed it using the external IP address of the instance, like this for example:

`http://216.3.128.12:40001/vnc.html?host=216.3.128.12&port=40001`

**Comment by willkessler** [comment]
Thanks-- that'll help somebody.
