### ISSUE TITLE
Setup.sh running problem

### ISSUE THREAD

**Issue by zengzhi2015** [willkessler/nvidia-docker-novnc#5]
Hi, friend! Thanks for your brilliant job first. But I have encountered several problem when running setup.sh. Could you please help me?
I run exactly the same hardware settings and software settings but problems occurs.
![30c8dc92-0b9b-4f10-94db-2b93223f72fd](https://user-images.githubusercontent.com/15316441/47265940-525ae500-d562-11e8-80f8-4441bf3eabdd.jpeg)
Problem may caused by errors in previous steps as follows: (I am not sure)
![bc54ebed-cd68-4323-9791-7192fc0ff747](https://user-images.githubusercontent.com/15316441/47265977-7d453900-d562-11e8-9e6a-aacf3e418516.png)
![5c263beb-a80f-4e93-a3e1-6154cd20c4d8](https://user-images.githubusercontent.com/15316441/47265978-7d453900-d562-11e8-9723-6663c1c9162e.png)
![a6e9ad2a-aea7-47f6-a901-28442efd119f](https://user-images.githubusercontent.com/15316441/47265979-7dddcf80-d562-11e8-91d6-9e66a17661f6.png)
![c6a6b267-82b6-41ff-9dd2-af842e561ca2](https://user-images.githubusercontent.com/15316441/47265980-7dddcf80-d562-11e8-934b-f002bab5ad7d.png)
![c0002720-0343-41e5-a1ba-72fee29195dc](https://user-images.githubusercontent.com/15316441/47265981-7dddcf80-d562-11e8-8b37-ba40dac73d3f.png)
![66176792-435b-45a4-817a-f6b5e08de755](https://user-images.githubusercontent.com/15316441/47265982-7e766600-d562-11e8-8abc-3c0f850fedf3.png)
![7a9f3d4e-1e70-4eff-a6b7-d9f9866f8915](https://user-images.githubusercontent.com/15316441/47265984-7e766600-d562-11e8-82a5-fca74e3cf2e9.png)
![cb49d579-edce-45c2-b94c-0609c954cc0a](https://user-images.githubusercontent.com/15316441/47265986-7f0efc80-d562-11e8-9b11-1fe403dfc690.png)
![95694e26-0952-4a9d-9ade-2a97ba49def3](https://user-images.githubusercontent.com/15316441/47265987-7fa79300-d562-11e8-8409-dbf45b8bb145.png)
![21cbe7a1-f863-474b-8da4-b88505e3346f](https://user-images.githubusercontent.com/15316441/47265988-7fa79300-d562-11e8-980a-ce27fd8cf886.png)
![885cc353-22c9-4285-bdd2-18e31d81cfe5](https://user-images.githubusercontent.com/15316441/47265989-7fa79300-d562-11e8-8531-828a64e8890a.png)

**Comment by slessans** [comment]
I've experienced the same problem, did you figure out the issue?

**Comment by willkessler** [comment]
I assumed you ran the all the procedures as root?

`sudo su - root` before beginning everything.

**Comment by slessans** [comment]
Running as root doesn't make a difference -- the error comes from the docker image build.

The `ros-kinetic-realsense` package is missing -- I think one of the turtlebot packages needs it. I dont need any of them so i removed them from the dockerfile:

```
RUN echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > \
    /etc/apt/sources.list.d/ros-latest.list && \
    apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116 && \
    apt-get update -y && \
    apt-get install -y ros-kinetic-desktop-full && \
    apt-get install -y ros-kinetic-roscpp && \
    apt-get install -y ros-kinetic-geometry-msgs && \
    apt-get install -y ros-kinetic-gazebo-ros && \
    apt-get install -y ros-kinetic-xacro && \
    rosdep init && \
    rosdep update && \
    echo "source /opt/ros/kinetic/setup.bash" >> /root/.bashrc
```

Since I removed most of the installs, I cant confirm with certainty which of those packages was causing the issue.

Hope this helps

**Comment by willkessler** [comment]
We found that we are able to get past the realsense issues with this in the Dockerfile:

```
# Tip on how to get turtle/librealsense to work: https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key C8B3A55A6F3EFCDE
RUN bash -c 'echo "deb http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo $(lsb_release -cs) main" > /etc/apt/sources.list.d/realsense-public.list'
RUN apt-get update

# install linux-kernel-headers on host
RUN apt-get install -y linux-headers-$(uname -r)

# install librealsense2
RUN apt-get install -y librealsense2 librealsense2-dkms librealsense2-utils realsense-uvcvideo

# add current user to video group
# RUN usermod -a -G video $USER
# RUN getent group video

RUN modinfo uvcvideo | grep "version:"

RUN echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > \
    /etc/apt/sources.list.d/ros-latest.list && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116 && \
    apt-get update -y && \
    apt-get install -y ros-kinetic-desktop-full && \
    apt-get install -y ros-kinetic-navigation && \
    apt-get install -y ros-kinetic-roscpp && \
    apt-get install -y ros-kinetic-joy && \
    apt-get install -y ros-kinetic-kobuki-safety-controller && \
    apt-get install -y ros-kinetic-yocs-velocity-smoother && \
    apt-get install -y ros-kinetic-turtlebot-bringup && \
    apt-get install -y ros-kinetic-geometry-msgs && \
    apt-get install -y ros-kinetic-yocs-cmd-vel-mux && \
    apt-get install -y ros-kinetic-diagnostic-aggregator && \
    apt-get install -y ros-kinetic-depthimage-to-laserscan && \
    apt-get install -y ros-kinetic-gazebo-ros && \
    apt-get install -y ros-kinetic-kobuki-gazebo-plugins && \
    apt-get install -y ros-kinetic-robot-pose-ekf && \
    apt-get install -y ros-kinetic-robot-state-publisher && \
    apt-get install -y ros-kinetic-turtlebot-description && \
    apt-get install -y ros-kinetic-turtlebot-navigation && \
    apt-get install -y ros-kinetic-xacro && \
    apt-get install -y ros-kinetic-rtabmap-ros && \
    apt-get install -y ros-kinetic-moveit && \
    apt-get install -y ros-kinetic-velocity-* && \
    apt-get install -y ros-kinetic-effort-* && \
    apt-get install -y ros-kinetic-joint-* && \
    apt-get install -y ros-kinetic-gazebo-ros-* && \
    apt-get install -y ros-kinetic-position-* && \
    rosdep init && \
    rosdep update
```

**Comment by trevorrobertsjr** [comment]
Sorry to resurrect an old thread, but posting what worked for me in case anyone else runs into it:

On the **# Install ROS** step, I found out from the ROS forums there is an issue with the GPG key, and I added the following line under apt-key...
curl https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - && \

The image build succeeds after that, and then you can run the container.
